# Generated by Django 3.1 on 2025-12-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('value', models.IntegerField(verbose_name='数值')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '柱状图数据',
                'verbose_name_plural': '柱状图数据',
                'db_table': 'bar_data',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='城市名称')),
                ('population', models.IntegerField(verbose_name='人口数量（万人）')),
                ('gdp', models.CharField(max_length=50, verbose_name='GDP')),
                ('area', models.CharField(max_length=50, verbose_name='面积')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'cities',
                'ordering': ['-population'],
            },
        ),
        migrations.CreateModel(
            name='LineChartData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='索引')),
                ('value', models.FloatField(verbose_name='数值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '折线图数据',
                'verbose_name_plural': '折线图数据',
                'db_table': 'line_chart_data',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='PieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('value', models.IntegerField(verbose_name='数值')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '饼图数据',
                'verbose_name_plural': '饼图数据',
                'db_table': 'pie_data',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='收益总计（亿万元）')),
                ('company_count', models.IntegerField(verbose_name='企业数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '统计数据',
                'verbose_name_plural': '统计数据',
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('patent_number', models.CharField(max_length=50, verbose_name='专利编号')),
                ('penalty_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='处罚金额')),
                ('year_over_year_percent', models.FloatField(verbose_name='同比百分比')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '表格数据',
                'verbose_name_plural': '表格数据',
                'db_table': 'table_data',
                'ordering': ['-penalty_amount'],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10, verbose_name='日期')),
                ('current_year_value', models.FloatField(verbose_name='今年同期值')),
                ('last_year_value', models.FloatField(verbose_name='去年同期值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '时间序列数据',
                'verbose_name_plural': '时间序列数据',
                'db_table': 'time_series_data',
                'ordering': ['date'],
            },
        ),
    ]
